### PR TITLE
feat: add policies

### LINKED ISSUE #33: How should I use batch operations？ it seems that there is no “add_policies” method
What should I do if I implement it myself

### PR DESCRIPTION
**Pull request by wakemaster39**
resolves #33

### CODE REVIEW

**Comment by hsluoyz** [comment]
@wakemaster39 plz:

1. Fix the CI error.
2. Link your github account with your git committer, to show the avatar:

image

**Comment by hsluoyz** [comment]
@techoner @Zxilly plz review.

**Comment by wakemaster39** [comment]
Does that clean up the author for you? Came from my work laptop so hard to keep it all in sync

**Comment by wakemaster39** [comment]
Python 3.4 CI failure seems out of the realm of fixing outside of dropping 3.4 support

**Comment by hsluoyz** [comment]
> Python 3.4 CI failure seems out of the realm of fixing outside of dropping 3.4 support

I have a question. Why only this PR failed Py 3.4 CI? I saw our master HEAD is OK. So strange.

**Comment by hsluoyz** [comment]
> Python 3.4 CI failure seems out of the realm of fixing outside of dropping 3.4 support

@wakemaster39 I have fixed the CI in another PR: https://github.com/pycasbin/sqlalchemy-adapter/pull/35 can you re-send a new PR to trigger the new CI?

**Pull request merged**
