### PR TITLE
fix `remove_policies`

### PR DESCRIPTION
**Pull request by sunhs**
Fix: https://github.com/pycasbin/sqlalchemy-adapter/issues/38

### CODE REVIEW

**Comment by hsluoyz** [comment]
@sunhs plz link git to your github account:

image

**Comment by sunhs** [comment]
@hsluoyz Sorry for creating the mess. My bad.

**Comment by hsluoyz** [comment]
That's fine:) Closed for now. You can rearrange your code and then make a new PR.

**Comment by hsluoyz** [comment]
Replaced by: https://github.com/pycasbin/sqlalchemy-adapter/pull/40

**Pull request closed without merging**
