### PR TITLE
Filtered Policy Support

### PR DESCRIPTION
**Pull request by wakemaster39**
Add support for filter policies recently merged into pycasbin

### CODE REVIEW

**Comment by hsluoyz** [comment]
@techoner @Xhy-5000 please review.

**Comment by Xhy-5000** [comment]
LGTM.

**Comment by hsluoyz** [comment]
@techoner

**Comment by hsluoyz** [comment]
Fix: https://github.com/pycasbin/sqlalchemy-adapter/issues/14

**Review by techoner — APPROVED** [review]

**Comment by hsluoyz** [comment]
Sorry that I found this PR broke our Travis CI, see: https://www.travis-ci.org/github/pycasbin/sqlalchemy-adapter/builds

I will revert all the PRs and commits starting from this PR.

image

**Pull request merged**
