### PR TITLE
feat: update_filtered_policies

### PR DESCRIPTION
**Pull request by Shivansh-yadav13**
- Not sure if this was also requested
- #53

### CODE REVIEW

**Comment by hsluoyz** [comment]
@leeqvip

**Review by leeqvip — CHANGES_REQUESTED** [review]
@Shivansh-yadav13  Please add unit tests.

**Comment by hsluoyz** [comment]
@Shivansh-yadav13 plz fix:

image

**Comment by hsluoyz** [comment]
@leeqvip

**Review by leeqvip — APPROVED** [review]

**Pull request merged**
