### PR TITLE
feat: allow CasbinRule customization

### LINKED ISSUE #12: Support Customization of CasbinRule class
Right now, CasbinRule has its own `declarative_base` that is hard coded down in all levels of the code.

Situations come up in use where you want to have your own class for various reasons such as a single declarative base. Rather than forcing a copy and pasting of the entire adapter and making your own. Allow setting the class yourself and all other logic renames usable.

### PR DESCRIPTION
**Pull request by wakemaster39**
Resolves #12

### CODE REVIEW

**Comment by hsluoyz** [comment]
@techoner please review.

**Comment by techoner** [comment]
@wakemaster39 Would it be better to `provide a set_db_class()` ?

**Comment by hsluoyz** [comment]
@wakemaster39 any update?

**Comment by wakemaster39** [comment]
Sorry this got lost in my updates, when you say `set_db_class` do you mean a function on the Adapter?

I would rather pass it in at the constructor level and use the existing `CasbinRule` as the default. I think that makes the most sense to me, but I could be convinced to do it as a function as well.

**Comment by hsluoyz** [comment]
@techoner

**Pull request merged**
