### PR TITLE
ci: migrate from travis-ci to Github Actions

### PR DESCRIPTION
**Pull request by ffyuanda**
Fix: #42 

Signed-off-by: ffyuanda <46557895+ffyuanda@users.noreply.github.com>

### CODE REVIEW

**Review by hsluoyz — CHANGES_REQUESTED** [review]
README badge is not updated

**Comment by ffyuanda** [comment]
@hsluoyz I think that is because I cannot actually push to PyPI server
image

**Comment by hsluoyz** [comment]
@ffyuanda I mean this one: https://github.com/pycasbin/sqlalchemy-adapter

image

**Comment by ffyuanda** [comment]
@hsluoyz the badge will be up once merged

**Review by hsluoyz — APPROVED** [review]

**Pull request merged**
